# Generated by Django 4.1.13 on 2023-11-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_room_room_type_remove_customuser_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hotel_logo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_logos/'),
        ),
    ]
