# Generated by Django 4.1.13 on 2023-11-27 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_hotel_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=20, unique=True)),
                ('services', models.ManyToManyField(choices=[('Resturant', 'Resturant'), ('swimming-Pool', 'Swimming Pool'), ('bar', 'Bar')], to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_setup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.hotelsetup')),
            ],
        ),
    ]
