# Generated by Django 4.1.13 on 2023-11-27 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hotelsetup_roompertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roompertype',
            name='hotel_setup',
        ),
        migrations.AddField(
            model_name='customuser',
            name='room_type',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='rooms_per_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.roompertype'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='services',
            field=models.ManyToManyField(blank=True, choices=[('Resturant', 'Resturant'), ('swimming-Pool', 'Swimming Pool'), ('bar', 'Bar')], to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roompertype',
            name='room_per_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HotelSetup',
        ),
    ]
