# Generated by Django 4.1.13 on 2023-11-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_roompertype_hotel_setup_customuser_room_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='room_type',
            field=models.CharField(choices=[('Delux', 'Delux'), ('Semi-Delux', 'Semi-Delux'), ('AC', 'AC'), ('Non-AC', 'Non-AC'), ('Standard', 'Standard')], max_length=20, unique=True),
        ),
    ]
