# Generated by Django 4.1.13 on 2023-11-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('house-keeping', 'House-Keeping'), ('Laundry-staff', 'laundry-staff'), ('chef', 'chef'), ('Room-attendent', 'room-attendent'), ('hotel-recptionist', 'hotel-recptionist')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='staff_email',
            field=models.EmailField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
