# Generated by Django 4.1.13 on 2023-11-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_role_customuser_staff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='staff_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
