# Generated by Django 4.1.13 on 2023-11-27 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('House-Keeping', 'House-Keeping'), ('Laundry-Staff', 'Laundry-Staff'), ('Chef', 'Chef'), ('Room-Attendant', 'Room-Attendant'), ('Hotel-Receptionist', 'Hotel-Receptionist')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='services',
            field=models.ManyToManyField(blank=True, choices=[('Restaurant', 'Restaurant'), ('Swimming-Pool', 'Swimming Pool'), ('Bar', 'Bar')], to=settings.AUTH_USER_MODEL),
        ),
    ]
