# Generated by Django 4.1.13 on 2023-11-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_role_alter_customuser_staff_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompertype',
            name='room_per_type',
            field=models.CharField(max_length=10),
        ),
    ]
