# Generated by Django 4.1.13 on 2023-11-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_room_per_type_roompertype_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='room_type',
            field=models.CharField(blank=True, choices=[('Delux', 'Delux'), ('Semi-Delux', 'Semi-Delux'), ('AC', 'AC'), ('Non-AC', 'Non-AC'), ('Standard', 'Standard')], max_length=20, null=True, unique=True),
        ),
    ]
