# Generated by Django 4.1.13 on 2023-11-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuser_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager'), ('House-Keeping', 'House-Keeping'), ('Laundry-Staff', 'Laundry-Staff'), ('Chef', 'Chef'), ('Room-Attendant', 'Room-Attendant'), ('Hotel-Receptionist', 'Hotel-Receptionist')], default=None, max_length=20, null=True),
        ),
    ]
