# Generated by Django 4.1.13 on 2023-11-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_email',
            field=models.EmailField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='staff_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
