# Generated by Django 4.1.13 on 2023-11-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_customuser_staff_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='roompertype',
            name='room_numbers',
            field=models.ManyToManyField(blank=True, to='accounts.room'),
        ),
    ]
