# Generated by Django 4.1.13 on 2023-11-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_room_roompertype_room_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='room_numbers',
            field=models.ManyToManyField(blank=True, to='accounts.room'),
        ),
    ]
