# Generated by Django 4.1.13 on 2023-11-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_customuser_room_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompertype',
            name='room_type',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
