# Generated by Django 4.1.13 on 2023-11-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_roompertype_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='room_numbers',
        ),
        migrations.RemoveField(
            model_name='roompertype',
            name='room_numbers',
        ),
        migrations.AlterField(
            model_name='roompertype',
            name='room_type',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
