# Generated by Django 4.1.13 on 2023-11-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_customuser_room_numbers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rooms_per_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='room_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='room_type',
            field=models.CharField(blank=True, choices=[('DEL', 'Delux'), ('SND', 'Standard'), ('AC', 'AC'), ('Non-AC', 'Non-AC'), ('Semi_delux', 'Semi-Delux')], max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='services',
        ),
        migrations.DeleteModel(
            name='RoomPerType',
        ),
        migrations.AddField(
            model_name='customuser',
            name='services',
            field=models.CharField(blank=True, choices=[('RES', 'Resturant'), ('SP', 'Swimming-Pool'), ('Bar', 'Bar'), ('Laundary', 'Laundary'), ('Parking', 'Parking')], max_length=10, null=True),
        ),
    ]
