# Generated by Django 4.1.13 on 2023-11-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
