# Generated by Django 4.1.13 on 2023-11-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_signed_out',
            field=models.BooleanField(default=False),
        ),
    ]
