# Generated by Django 4.1.13 on 2023-11-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_customuser_is_signed_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_signed_out',
            field=models.BooleanField(default=True),
        ),
    ]
