# Generated by Django 4.1.13 on 2023-11-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_tokenblacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_signed_out',
            field=models.BooleanField(default=False),
        ),
    ]
