# Generated by Django 4.2.7 on 2023-11-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_customuser_is_signed_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_signed_out',
        ),
    ]
