# Generated by Django 4.2.7 on 2023-11-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_remove_customuser_role_customuser_staff_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenBlacklist',
        ),
    ]
