# Generated by Django 4.1.13 on 2023-11-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='room_type',
            field=models.CharField(choices=[('DEL', 'Delux'), ('SND', 'Standard'), ('AC', 'AC'), ('Non-AC', 'Non-AC'), ('Semi_delux', 'Semi-Delux')], max_length=10, null=True),
        ),
    ]
