# Generated by Django 4.1.13 on 2023-11-30 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_customuser_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEL', 'Delux'), ('SND', 'Standard'), ('AC', 'AC'), ('Non-AC', 'Non-AC'), ('Semi_delux', 'Semi-Delux')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='room_type',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.roomtype')),
            ],
        ),
    ]
