# Generated by Django 4.1.13 on 2023-11-30 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(db_column='room_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='accounts.roomtype'),
        ),
    ]
