# Generated by Django 4.1.13 on 2023-12-01 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='services',
            field=models.CharField(blank=True, choices=[('RES', 'Resturant'), ('SP', 'Swimming-Pool'), ('Bar', 'Bar'), ('Laundary', 'Laundary'), ('Parking', 'Parking')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.roomtype'),
        ),
    ]
