# Generated by Django 4.1.13 on 2023-12-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager'), ('House-Keeping', 'House-Keeping'), ('Laundry-Staff', 'Laundry-Staff'), ('Chef', 'Chef'), ('Room-Attendant', 'Room-Attendant'), ('Hotel-Receptionist', 'Hotel-Receptionist'), ('Res-staff', 'Restaurant-Staff')], max_length=20, null=True),
        ),
    ]
