# Generated by Django 4.1.13 on 2023-12-01 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_alter_customuser_hotel_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='staff_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='staff_name',
        ),
        migrations.CreateModel(
            name='RoomNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_Data', to='accounts.roomtype')),
            ],
        ),
    ]
