# Generated by Django 4.1.13 on 2023-12-01 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_customuser_room_number_customuser_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomnumber',
            name='room_type',
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_data', to='accounts.roomnumber'),
        ),
    ]
