# Generated by Django 4.1.13 on 2023-12-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_roomtype_room_number_alter_roomtype_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomnumber',
            name='room_number',
            field=models.CharField(max_length=10000),
        ),
    ]
