# Generated by Django 4.1.13 on 2023-12-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_alter_roomnumber_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='room_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.roomtype'),
        ),
    ]
