# Generated by Django 4.1.13 on 2023-12-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_remove_customuser_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='room_numbers',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='room_types',
        ),
        migrations.DeleteModel(
            name='RoomNumber',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
