# Generated by Django 4.1.13 on 2023-12-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_customuser_total_rooms_roomdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='total_rooms',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
