# Generated by Django 4.1.13 on 2023-12-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_alter_customuser_total_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='total_rooms',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
